# Generated by Django 4.1.3 on 2022-11-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('remaining', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
    ]
