# Generated by Django 4.1.3 on 2022-11-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
